name: Java Spring Boot CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [11]

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'adopt'
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.TOKEN }}
          overwrite-settings: true

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Build and Push image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "actions-repo" --password-stdin
          docker image build -t actions-repo/product-app:latest .
          docker push actions-repo/product-app:latest
   
       

#      - name: Log in to Docker Hub
#        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

#      - name: Push Docker image
#        run: |
#          docker tag product-app:latest surajc7723/actions-repo/product-app:latest
#          docker push surajc7723/actions-repo/product-app:latest


