name: CI

on: [push, pull_request]

jobs:
  build:
    uses: Sakonyama-Store/org-actions/.github/workflows/java-springboot-ci.yml@main
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
